# Generated by Django 3.1.2 on 2020-10-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=18, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=18, null=True)),
                ('latest_trade', models.DateTimeField()),
                ('high', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=18, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=18, null=True)),
                ('close', models.DecimalField(decimal_places=3, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=18)),
                ('currency_volume', models.DecimalField(decimal_places=3, max_digits=18)),
                ('weighted_price', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=18, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('avg', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_record', models.BooleanField(default=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_market', to='market.market')),
            ],
        ),
    ]
